SIMPLE_SENTENCE_LABEL = 'simple_sentnece'
COMPLEX_SENTENCE_LABEL = 'complex_sentnece'


SYMBOL_GO = '#GO#'
SYMBOL_PAD = '#PAD#'
SYMBOL_UNK = '#UNK#'
SYMBOL_START = '#BOS#'
SYMBOL_END = '#EOS#'
SYMBOL_NUM = '#NUM#'
SYMBOL_QUOTE = '#QUOT#'

REVERED_VOCAB_SIZE = 10

